//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.14 at 11:01:13 AM EET 
//


package com.nixsolutions.soap.wsdl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkerService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkerService">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="workerId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="user" type="{http://localhost:8080/serviceStation/soapws}UserService"/>
 *         &lt;element name="workerSpecialization" type="{http://localhost:8080/serviceStation/soapws}WorkerSpecializationService"/>
 *         &lt;element name="workerStatus" type="{http://localhost:8080/serviceStation/soapws}WorkerStatusService"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkerService", propOrder = {
    "workerId",
    "lastName",
    "firstName",
    "phone",
    "user",
    "workerSpecialization",
    "workerStatus"
})
public class WorkerService {

    @XmlElement(required = true)
    protected BigInteger workerId;
    @XmlElement(required = true)
    protected String lastName;
    @XmlElement(required = true)
    protected String firstName;
    @XmlElement(required = true)
    protected String phone;
    @XmlElement(required = true)
    protected UserService user;
    @XmlElement(required = true)
    protected WorkerSpecializationService workerSpecialization;
    @XmlElement(required = true)
    protected WorkerStatusService workerStatus;

    /**
     * Gets the value of the workerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWorkerId() {
        return workerId;
    }

    /**
     * Sets the value of the workerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWorkerId(BigInteger value) {
        this.workerId = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link UserService }
     *     
     */
    public UserService getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserService }
     *     
     */
    public void setUser(UserService value) {
        this.user = value;
    }

    /**
     * Gets the value of the workerSpecialization property.
     * 
     * @return
     *     possible object is
     *     {@link WorkerSpecializationService }
     *     
     */
    public WorkerSpecializationService getWorkerSpecialization() {
        return workerSpecialization;
    }

    /**
     * Sets the value of the workerSpecialization property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkerSpecializationService }
     *     
     */
    public void setWorkerSpecialization(WorkerSpecializationService value) {
        this.workerSpecialization = value;
    }

    /**
     * Gets the value of the workerStatus property.
     * 
     * @return
     *     possible object is
     *     {@link WorkerStatusService }
     *     
     */
    public WorkerStatusService getWorkerStatus() {
        return workerStatus;
    }

    /**
     * Sets the value of the workerStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkerStatusService }
     *     
     */
    public void setWorkerStatus(WorkerStatusService value) {
        this.workerStatus = value;
    }

}
