//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.17 at 09:12:53 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/21_webservices-0.0.1-SNAPSHOT/ws/soap/user")
package localhost._8080._21_webservices_0_0_1_snapshot.ws.soap.user;
