//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.16 at 01:21:49 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.servicestation.nixsolutions.com/wssoap")
package com.nixsolutions.servicestation.wssoap;
