//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.14 at 10:04:02 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/21_webservices-0.0.1-SNAPSHOT/ws/soap/user")
package com.nixsolutions.studentgrade.webservice.soap;
